name: Quality Checks

on:
    workflow_dispatch: { }

    pull_request: {}
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    stan:
        name: PHP Stan
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
              with:
                php-version: 7.4
                coverage: none

            - name: Run PHP Stan
              run: composer phpstan-pr-analysis
